# Generated by Django 5.2.16 on 2026-07-25 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitee',
            fields=[
                ('id_activitee', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=150, unique=True, verbose_name='Service')),
                ('montantSC', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant standard')),
                ('budget_alloue', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget alloue')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('unique_par_employe', models.BooleanField(default=False, verbose_name='Non renouvelable')),
            ],
            options={
                'verbose_name': 'Activite',
                'verbose_name_plural': 'Activites',
                'db_table': 'activitee',
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('matricule', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('departement', models.CharField(db_index=True, max_length=100, verbose_name='Departement')),
                ('date_recrutement', models.DateField(verbose_name='Date de recrutement')),
                ('nb_enfants', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre d'enfants")),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'db_table': 'personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('montantTR', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant verse')),
                ('duree', models.PositiveSmallIntegerField(default=0, help_text='Duree en jours, 0 si non applicable', verbose_name='Duree (jours)')),
                ('date_transaction', models.DateField(verbose_name='Date de la transaction')),
                ('annee', models.PositiveSmallIntegerField(db_index=True, verbose_name='Annee')),
                ('id_activitee', models.ForeignKey(db_column='id_activitee', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.activitee', verbose_name='Activite')),
                ('matricule', models.ForeignKey(db_column='matricule', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.personnel', verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-date_transaction', '-id_transaction'],
                'indexes': [models.Index(fields=['matricule', 'id_activitee'], name='transaction_matricu_9771f5_idx'), models.Index(fields=['id_activitee', 'annee'], name='transaction_id_acti_b65ff2_idx')],
            },
        ),
    ]
