# Generated by Django 5.2.16 on 2026-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], db_index=True, default='', max_length=1, verbose_name='Sexe'),
        ),
    ]
